const { z } = require('zod');

 const SubjectsEnum = z.enum([
    "PYQ",
    "Enginnering Chemestry",
    "Introduction to Computer Programming and Data Structure",
    "Enginnering Mathamtics - I",
    "Materials Science",
    "Environment and Ecology",
    "Electrical Engineering & Measurements",

    "Science of Living Systems",
    "Enginnering Mechanics",
    "English for Communication",
    "Enginnering Physics",
    "Workshop Practicals",
    "Enginnering Mathamtics - II",
    "Basic Electronics and Instrumentaion",

    "Electroniccs & Instrumantation",
    "Analog and Digital Electronics",
    "Electromagnetic Field Theory",
    "Electrical Circuit and Systems",
    "Signal System",
    "Advance Engineering Mathematics",
    "Industrial Economics",

    "Electrical Machine-I",
    "Power System-I",
    "Power Electronics",
    "Control Systems",
    "Electrical Measurement and Measuring Instruments",
    "Intellectual Property Rights",
    "Computer Architecture & Operating System ",

    "Artificial Intelligence",
    "Renewable Energy Resources and Converters",
    "Power Generation and Economics",
    "Electrical Machine-II",
    "Advance Power Electronics",
    "Advance Control Systems",
    "Power System-II",

    "Power System Protection",
    "Microprocessors & Micro-controllers",
    "Computer Aided Power System",
    "Electrical Drives",
    "FACTS Devices",
    "Entrepreneurship & Ethics",
    "HVAC & DC Transmission",

    "VLSI Design Flow – RTL to GDS",
    "Communication System",
    "High Voltage Engineering",
    "Modern Power System Practice",
    "Power System Operation and Control",

    
    "Signal and System",
    "Solid State Device",
    "Data Structure and Program Design",
    "Network Theory and Systems",
    "Probability and Stochastic Process",
    "Digital Circuits and System Design",

    "Analog Electronics",
    "Analog Communication",
    "Microprocessor and Microcontroller",
    "Electromagnetic Field Theory",
    "Elective-I: Soft Computing",
    "Matlab and Python",

    "Intellectual Property Rights",
    "Control System Engineering",
    "Embedded System and IOT",
    "Digital Communication",
    "VLSI Design",

    "Digital Signal Processing",
    "RF & Microwave Engineering",
    "Computer Communication & Networking",
    "VHDL and Verilog",
    "Information Theory & Coding",
    "Introduction to Soft Skills",

    "Optical Communication",
    "Mobile and Wireless Communication",
    "Satellite Communication",
    "Soft Computing",
    "Principles of Management",
    "Entrepreneurship",

    "Digital IC Design",
    "Sensors and Transducers",


    "Mechanics of Solid-I",
    "Experimental Method for Engineers",
    "Fluid Mechanics",
    "Dynamics of Mechanical System",
    "Economics for Engineers",

    "Bio-Mechanics",
    "Integrated System Design",
    "Mechanics of Solids-II",
    "Product Design & Development",
    "Data Structures & Operating Systems",
    "Engineering Ethics and IPR ",


    "Survey",
    "Strength of Materials",
    "Building Materials and Concrete Technology",
    "Enginnering Geology and Seismology",
    "Fluid Mechanics-I",

    "Building Planning and Drawing Sessional",
    "Construction Technology",
    "Structural Analysis-I",
    "Geotechnical Engineering-I",
    "Fluid Mechanics-II",
    "Transportation Engineering-I",
    "Intellectual Property Rights",

    "Civil Construction Planning and Project Management",
    "Design for Concrete Structures",
    "Environmental Engineering-I",
    "Transportation Engineering-II",
    "Engineering Hydrology",
    "Structural Analysis-II",

    "Prestressed Concrete Design",
    "Advanced Design of Concrete Structure",
    "Embankment Dam Engineering",
    "An Introduction to Unsaturated Soil Mechanics",
    "PE-I A",
    "PE-I D",
    "PE-I C",
    "PE-I B",
    "Irrigation & Hydraulic Structures",
    "Geotechnical Engineering–II",
    "Environmental Engineering-II",
    "Design of Steel Structures",

    "Civil Construction, Planning and Management",
    "Irrigation Engineering",
    "Transportation Engineering-II",
    "Bridge Engineering",
    "Pre-Stress Concrete Design",
    "Structural Dynamics and Earthquake Resistant Design",
    "Construction Safety and Fire Engineering",
    "Traffic Engineering",
    "Rock Engineering",
    "Pollution – Disease and Climate Change",
    "Planning for Sustainable Development",
    "Engineering Risk – Benefit Analysis",

    "Port and Harbour Engineering",
    "Solid Waste Management",
    "Disaster Management",
    "Environmental Pollution and Control",


    "Mechanics of solids-I",
    "Enginnering Thermodynamics",
    "Fluid Mechanics",
    "Industrial Economics",
    "Manufacturing Process-I",
    
    "Phase Transformation and Heat Treatment of Materials",
    "Manufacturing Process-II",
    "Applied Thermodynamics-I",
    "Heat and Mass Transfer",
    "Theory of Machines",
    "Mechanics of solids-II",
    "Analog Communication",

    "Design of Machine Elements",
    "Fluid Machinery",
    "Indian Art/Culture",
    "Industrial Engineering",
    "Intellectual Property Rights",

    "Design of Mechanical Systems",
    "Applied Thermodynamics-II",
    "Solar Energy Process",
    "Computational Fluid Dynamics",
    "Gas Dynamics",
    "Robotics and Automation",
    "Mechanics of Composite Materials",
    "Finite Element Method",

    "Computer Aided Design and Manufacturing",
    "Computational Mechanics",
    "Ancient Indian Science & Technology",
    "Robotics and its Applications",
    "Tribology)",
    "Automobile Engineering",


    "Digital System Design",
    "Design and Analysis of Algorithms",
    "Data Structures",
    "Introduction to Soft Skills",
    "Probability and Statistics",
    "Discrete Mathematics",

    "Database Management Systems",
    "Computer Organization and Architecture",
    "Operating Systems",
    "Artificial Intelligence",
    "Internet and Web Technology",

    "Object Oriented Programming using Java",
    "Intellectual Property Rights",
    "Microprocessors and Microcontrollers",
    "Machine Learning",
    "Software Engineering",
    "Theory of Computation",
    "Capstone Project-I",

    "Compiler Design",
    "Computer Networks",
    "Capstone Project-II",
    "Data Warehousing and Data Mining",
    "Information Theory and Coding",
    "Digital Image Processing",

    "Artificial Intelligence",
    "Web Technology",
    "Internet of Things",
    "Organizational Behaviour and Industrial Psychology",
    "Industrial Economics",

    "Blockchain and its Applications",
    "Deep Learning",



    "Principles of Physical Metallurgy",
    "Thermodynamics of Materials",
    "Geology and Mineral Processing",
    "Introduction to Soft Skills",
    "Engineering Mathematics-III",
    "Physics of Materials",
    "New Generation Fuel, Furnace and Refractories",

    "Deformation Behavior and Processing of Materials",
    "Electrical Machines-I",
    "Transport Phenomena in Materials Processing ",
    "Iron Making",
    "Materials Characterization",
    "Phase Transformation and Heat Treatment of Materials",

    "Behaviour of Materials toward Failure",
    "Fluid Machinery",
    "Manufacturing Process in Metallurgy",
    "Extraction of Non-Ferrous Metals",
    "Geo-metallurgy",
    "Testing of Materials",
    "Tribology of Materials",

    "Materials Selection and Design",
    "Advanced Engineering Materials",
    "Surface Science and Engineering",
    "Powder Metallurgy and Ceramics",
    "Intellectual Property Rights",
    "Super Alloys",
    "Materials for Automatic Aerospace Application",
    "Materials for Strategic Applications",

    "Environmental Degradation of Materials and its Protection",
    "Advanced Engineering Materials",
    "Creep, Fatigue and Fracture",
    "Continuous Casting of Steel",
    "Principles of Management",
    "Non-Destructive Testing",


    "Mechanics of Solid",
    "Engineering Thermodynamics",
    "Measurement and Metrology",
    "Theory of Machines",
    "Manufacturing Process-I",
    "Indian Art Culture and Science",

    "Engineering Economics and Accountancy",
    "Production Management",
    "Design of Machine Elements",
    "Fluid Mechanics and Machinery",
    "Manufacturing Process-II",

    "CAD/CAM",
    "Supply Chain Management",
    "Product Design and Development",
    "Operations Research",
    "Fundamentals of Intellectual Property Rights",
    "Surface Engineering",
    "Digital Manufacturing",

    "Non-Traditional Manufacturing Processes",
    "Metal Forming",
    "Design of Production Tooling",
    "Concurrent Engineering",
    "Project Management",
    "Concurrent Engineering",
    "Work System Design and Ergonomics",
    "Micro and Nano manufacturing",
    "Reliability Engineering",
    "Business Statistics",
    "Additive Manufacturing",
    "Soft Skills",

    "Automation and Robotics",
    "Supply Chain Management",
    "Precision Engineering",
    "Production Design and Process Planning",
    "Entrepreneurship Management",
    "Organizational Behaviour and Industrial Psychology",
    "Manufacturing of Composite Materials",
    "Advanced Welding Processes",
    "Work Study Design and Ergonomics"
] , {
    message : "Enter a valid subject"
});


module.exports = {SubjectsEnum}